# Generated by Django 3.2.9 on 2023-02-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_auto_20180501_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='extra_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='extra_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='statistic_info',
            field=models.JSONField(default=dict),
        ),
    ]
