# Generated by Django 3.2.9 on 2023-02-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0013_auto_20230210_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='extra_info',
        ),
    ]
