# Generated by Django 3.2.9 on 2023-02-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_problem_extra_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
