# Generated by Django 3.2.9 on 2023-02-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0017_problem_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='func_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_mode',
            field=models.IntegerField(default=0),
        ),
    ]
