# Generated by Django 3.2.9 on 2023-02-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0018_auto_20230217_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='segment_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='func_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
