# Generated by Django 3.2.9 on 2023-02-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0020_problem_judge_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='func_config',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='segment_config',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='test_mode',
        ),
    ]
